name: CI Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 — Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt yet"

      # Step 4 — Run unit tests
      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings || echo "Tests not found yet"

      # Step 5 — Save logs as artifacts
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: ./test-results/
          if-no-files-found: ignore